### ISSUE TITLE
[bug] verbal casting not working with localized chat by kreezxil

### ISSUE THREAD

**Issue by thekillergoose** [ssblur/scriptor#68] opened 2023-08-03 20:06 UTC
i found that the mod localized chat by kreezxil conflicts with verbal casting in scriptor. i have no idea what part of the mod causes the conflict all i know is that it disables verbal casting.

**Comment by ssblur** [comment] 2023-08-04 00:40
This is an interaction caused by Localized Chat, it cancels all chat messages and relays them manually, which prevents Scriptor from processing them. Looking into ways to circumvent this, but it seems unlikely this can be fixed without either minor changes to Localized Chat or some hackish cross-mod support.

**Comment by ssblur** [comment] 2023-10-15 23:26
Unfortunately there seems to be no clean way to circumvent this and explicit cross-mod support does not seem practical, apologies.

**Closed by ssblur** 2023-10-15 23:26 UTC
Labels: bug, cross-mod support
