### ISSUE TITLE
Spells problems 

### ISSUE THREAD

**Issue by VanCock** [ssblur/scriptor#36] opened 2023-04-10 13:59 UTC
So I was messing around with your wonderful mod (fabric 1.19.2 mod version 0.3.4) and few spells seem not to work (or they have extra steps I have to take that are hard to understand/reveal), for example Immolate, Charge Weapons and Great Smite may work but I just have no clue what they supposed to do (there was also self damage spell but I figured what I'd did, why does it even exist), or how to make them work, on the other hand Break Block and Healing Hands doesn't work at all (unless Healing Hands work only on other players then nvm),
Besides that I have to admit that spell writing is ridiculous, it's annoying but once you get hang of it it's duable, still not my favourite way to create spells but for sure most original.
I hope in the future there will be improvements to that system (I would love to hear what do you plan to implement), of course more awesome spells, and maybe some other magical components like staffs, robes, runes n such (a way to have spell beacons via let's say lectern seems vanilla+ and would be great addition).

**Comment by ssblur** [comment] 2023-04-10 14:31
Immolate sets the casting player on fire, and as such will not work in Creative. Were you using this spell in Creative?

Charge Weapons, when used as an item, will provide a message informing you that it can't be used this way. Please try using an Identify scroll on it.

Greater Smite notes that the spell fizzles when used. Information is provided in-game on why this happens. This is intended to both provide access to strong components and teach players about fizzling and help them craft better spells.

Break Block will only work on blocks which can be broken by wooden tools or less.

Healing Hands only works on other entities.

Spell writing is constantly undergoing improvements, as this mod is still very early in development.

Overall, I would suggest using Identify Scrolls. They were specifically added to assist when a spell seems not to work, and may be helpful to you in discovering and crafting spells.

@VanCock The only likely bug here seems to be with Break Block. Does it work on Dirt / other blocks you can break with your hands or wooden tools? Are there other mods installed which affect break permissions (chunk claims, progression mods, etc.)?

**Comment by VanCock** [comment] 2023-04-10 14:43
That explains Immolate, kinda useless but what do I know, 

I was testing both Healing Hands and Break Block and yes Break Block doesn't work on wood, dirt stone and anything of that type (no other mods were present), Healing Hands may not work in creative, but I'm still not too sure about it, 

In terms of scrolls only help they have ever provided me is with Hammer spell informing me I need full health, other than that their "hints" are often unclear and doesn't help much, 

I hope you can fixed the mentioned problems (or tell me what I was doing wrong) and I'm quite excited to see what is planned for future, as so far your mod is quite promising.

**Comment by ssblur** [comment] 2023-04-11 03:58
This sounds like it may be a networking issue, but I was unable to replicate on 0.3.4 with Architectury API 6.5.77 and Fabric API 0.76.0 on Fabric version 0.14.12 for 1.19.2, either on a standalone client or on a client connected to a dedicated server. This might happen if your game is lagging a lot / you have very high ping and you look away from your target too quickly. Unfortunately if this is the case, there isn't much way to prevent this with the way spells currently resolve.

After verifying you are on the latest versions of these libraries, you can test this by using Break Block on a block and continuing to look at it for a few seconds. If this causes the spell to work, this is more than likely caused by high ping or a slow game/server. Can you try this, and if the issue persists, provide your most recent game log as an attachment to this issue? (After your game closes, this will be located in logs/latest.log in your minecraft instance's directory) 

Thank you in advance!

**Comment by VanCock** [comment] 2023-04-11 08:48
So I went in (reinstalled the mod, new world and had anchor in addition if that matters to you) and "Break Block" works just fine, it may have to do something with randomised spell patterns I think, but I swear it didn't worked before and now it just does for some reason, I bet it will refuse to work next time I try it, but for now let's just drop it,

On the other hand while typing "Charge Weapon" pattern in chat it kicked me from server... even tho I was in single player so that may be dedicated server problem, plus I still have no idea what does it supposed to do, all it says is I should try it somewhere else, BUT WHERE?!

Other than that it's mostly fine, truly a rollercoaster with this mod, one day spells work and are easy to write and understand second I struggle with basic spells, for the love of God I just wasn't able to write working spell today, even tho I did it in the past many times, I see why it's still in beta, but I believe you can fix it somehow while keeping it relatively close to original idea, 

Cheers.  <3

**Comment by ssblur** [comment] 2023-04-11 15:35
Thank you, it looks like an error loading a rune was caught, but no details on the actual crash. I have generated and tested touch spells on ~20 worlds and not run into this issue so either a recent change fixed this or it is uncommon. I will be closing this issue for now, but if you encounter either of these issues again, do not hesitate to reopen it.

For future reference, world saves are located in `saves/[world name]` in your minecraft instance, or in `[world name]` (set in server.properties) in your server directory. Inside this directory, scriptor data is located in the `data` directory and prefixed with `scriptor_`.

Also in the future, attaching the log file by dragging it into the text box or clicking the bar below it makes for a more readable issue.

Thank you for your work in helping me resolve this issue! I'm glad you're enjoying the mod so far and hope that you'll enjoy it more as it improves.

**Closed by ssblur** 2023-04-11 15:35 UTC
