### ISSUE TITLE
[bug] Bring from first full slot in inventory not working

### ISSUE THREAD

**Issue by KiloTheNeko** [ssblur/scriptor#80] opened 2023-10-22 19:13 UTC
**Mod Version (e.g. Fabric 0.3.4)**: v0.6.6-1.21.1

**What you expect to happen**:

"It will teleport an item from the first filled slot in a target inventory to the caster
Target inventories are like chests, furnaces, horses, mules, etc.
If there is no valid inventory, it will fall back to a normal bring spell, so it can also be used to teleport mobs to the caster" - the creator of the mod ssblur

**What actually happens**:
What actually happens, in detail. If you can, include steps here on how to reproduce the issue.

nothing .-. suprisingly it does cast but it just doesn't move any items

**Comment by ssblur** [comment] 2023-11-18 04:59
I cannot reproduce this issue in version 0.6.6 on Fabric or Forge. I recall you mentioning the spell color, so I have tested both with and without a color component.

What are you targeting with the spell and what are the specific components? Is this the default "Phantom Thief" spell? How are you casting this? I tested both from a book and verbally.

**Comment by ssblur** [comment] 2023-12-28 21:14
Closing this as it cannot be replicated in 1.20.1. If you encounter this issue again, please feel free to reopen.

**Closed by ssblur** 2023-12-28 21:14 UTC
Labels: bug
